packages:
  - .
  - packages/*
catalogs:
  ai:
    '@ai-sdk/anthropic': ^3.0.45
    '@ai-sdk/google': ^3.0.29
    '@ai-sdk/openai': ^3.0.30
    '@ai-sdk/react': ^3.0.93
    '@ai-sdk/zai': npm:zhipu-ai-provider@^0.2.2
    ai: ^6.0.91
  backend:
    drizzle-kit: ^0.31.9
    drizzle-orm: ^0.45.1
    drizzle-zod: ^0.8.3
    postgres: ^3.4.8
  dev:
    '@better-auth/cli': ^1.4.18
    '@sparticuz/chromium': ^143.0.4
    autoprefixer: ^10.4.24
    bumpp: ^10.4.1
    pncat: ^0.10.2
    shadcn: ^3.8.5
    simple-git-hooks: ^2.13.1
    supabase: ^2.76.10
    taze: ^19.9.2
    tsx: ^4.21.0
    typescript: ^5.9.3
  frontend:
    '@dnd-kit/core': ^6.3.1
    '@dnd-kit/sortable': ^10.0.0
    '@dnd-kit/utilities': ^3.2.2
    '@radix-ui/react-use-controllable-state': ^1.2.2
    '@streamdown/cjk': ^1.0.2
    '@streamdown/code': ^1.0.2
    '@streamdown/math': ^1.0.2
    '@streamdown/mermaid': ^1.0.2
    '@tailwindcss/postcss': ^4.2.0
    class-variance-authority: ^0.7.1
    clsx: ^2.1.1
    cmdk: ^1.1.1
    motion: ^12.34.2
    qrcode.react: ^4.2.0
    radix-ui: ^1.4.3
    react: ^19.2.4
    react-day-picker: ^9.13.2
    react-dom: ^19.2.4
    react-image-crop: ^11.0.10
    react-resizable-panels: 2.1.9
    sonner: ^2.0.7
    streamdown: ^2.2.0
    tailwind-merge: ^3.5.0
    tailwindcss: ^4.2.0
    tw-animate-css: ^1.4.0
    use-stick-to-bottom: ^1.1.3
    vaul: ^1.1.2
    zustand: ^5.0.11
  icons:
    '@iconify/react': ^6.0.2
    lucide-react: ^0.574.0
  lint:
    '@eslint-react/eslint-plugin': ^2.13.0
    '@octohash/eslint-config': ^0.2.3
    eslint: ^9.39.3
    eslint-config-hyoban: ^6.0.0-beta.18
    eslint-config-next: ^16.1.6
    eslint-plugin-better-tailwindcss: ^4.3.0
    eslint-plugin-format: ^1.4.0
    lint-staged: ^16.2.7
  prod:
    '@better-auth/ui': npm:@daveyplate/better-auth-ui@^3.3.15
    '@sparticuz/chromium-min': ^143.0.4
    '@supabase/ssr': ^0.8.0
    '@supabase/supabase-js': ^2.97.0
    bcrypt: ^6.0.0
    better-auth: ^1.4.18
    date-fns: ^4.1.0
    dexie: ^4.3.0
    lz-string: ^1.5.0
    nanoid: ^5.1.6
    next: ^16.1.6
    next-intl: ^4.8.3
    next-themes: ^0.4.6
    ofetch: ^1.5.1
    puppeteer-core: ^24.37.4
    usehooks-ts: ^3.1.1
    zod: ^4.3.6
  test:
    vitest: ^4.0.18
  types:
    '@types/bcrypt': ^6.0.0
    '@types/node': ^25.3.0
    '@types/react': ^19.2.14
    '@types/react-dom': ^19.2.3
ignoredBuiltDependencies:
  - better-sqlite3
  - bcrypt
  - core-js
  - esbuild
  - msw
  - sharp
  - simple-git-hooks
  - supabase
  - unrs-resolver
  - '@parcel/watcher'
  - '@prisma/client'
  - '@swc/core'
