packages:
  - .
  - packages/*
ignoredBuiltDependencies:
  - better-sqlite3
  - bcrypt
  - core-js
  - esbuild
  - msw
  - sharp
  - simple-git-hooks
  - supabase
  - unrs-resolver
  - '@parcel/watcher'
  - '@prisma/client'
  - '@swc/core'
catalogs:
  ai:
    '@ai-sdk/anthropic': ^3.0.28
    '@ai-sdk/google': ^3.0.15
    '@ai-sdk/openai': ^3.0.21
    '@ai-sdk/zai': npm:zhipu-ai-provider@^0.2.2
    ai: ^6.0.57
  auth:
    '@better-auth/cli': ^1.4.17
    '@better-auth/ui': npm:@daveyplate/better-auth-ui@^3.3.15
    better-auth: ^1.4.17
  cli:
    bumpp: ^10.4.0
    pncat: ^0.8.0
    taze: ^19.9.2
  database:
    '@supabase/ssr': ^0.8.0
    '@supabase/supabase-js': ^2.93.2
    drizzle-kit: ^0.31.8
    drizzle-orm: ^0.45.1
    postgres: ^3.4.8
    supabase: ^2.72.8
  export:
    '@sparticuz/chromium': ^143.0.4
    '@sparticuz/chromium-min': ^143.0.4
    puppeteer-core: ^24.36.1
  frontend:
    '@ai-sdk/react': ^3.0.79
    '@dnd-kit/core': ^6.3.1
    '@dnd-kit/sortable': ^9.0.0
    '@dnd-kit/utilities': ^3.2.2
    '@radix-ui/react-use-controllable-state': ^1.2.2
    cmdk: ^1.1.1
    motion: ^12.29.2
    qrcode.react: ^4.2.0
    radix-ui: ^1.4.3
    react: ^19.2.4
    react-day-picker: ^9.13.0
    react-dom: ^19.2.4
    react-image-crop: ^11.0.10
    react-resizable-panels: 2.1.9
    sonner: ^2.0.7
    zustand: ^5.0.10
  i18n:
    next-intl: ^4.7.0
  icons:
    '@iconify/react': ^6.0.2
    lucide-react: ^0.563.0
  lint:
    '@eslint-react/eslint-plugin': ^2.7.4
    eslint: ^9.39.2
    eslint-config-hyoban: ^6.0.0-beta.16
    eslint-config-next: ^16.1.6
    eslint-plugin-format: ^1.3.1
    lint-staged: ^16.2.7
    simple-git-hooks: ^2.13.1
  markdown:
    '@streamdown/cjk': ^1.0.1
    '@streamdown/code': ^1.0.1
    '@streamdown/math': ^1.0.1
    '@streamdown/mermaid': ^1.0.1
    streamdown: ^2.1.0
  network:
    ofetch: ^1.5.1
  next:
    next: ^16.1.6
    next-themes: ^0.4.6
  node:
    shadcn: ^3.7.0
  prod:
    use-stick-to-bottom: ^1.1.2
    usehooks-ts: ^3.1.1
    vaul: ^1.1.2
  script:
    tsx: ^4.21.0
  style:
    '@tailwindcss/postcss': ^4.1.18
    autoprefixer: ^10.4.23
    class-variance-authority: ^0.7.1
    clsx: ^2.1.1
    tailwind-merge: ^3.4.0
    tailwindcss: ^4.1.18
    tw-animate-css: ^1.4.0
  test:
    vitest: ^4.0.18
  tsc:
    typescript: ^5.9.3
  types:
    '@types/bcrypt': ^6.0.0
    '@types/node': ^25.0.10
    '@types/react': ^19.2.10
    '@types/react-dom': ^19.2.3
  utils:
    bcrypt: ^6.0.0
    date-fns: ^4.1.0
    dexie: ^4.3.0
    drizzle-zod: ^0.8.3
    lz-string: ^1.5.0
    nanoid: ^5.1.6
    zod: ^4.3.6
